add on_fail step

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -53,7 +53,7 @@ jobs:
           name: "Say World"
           command: "echo World!"
 
-          
+
   print_my_name:
     <<: *defaultCon
     steps:
@@ -98,6 +98,14 @@ jobs:
       - checkout
       - print_pipeline_id :
           to: ${CIRCLE_WORKFLOW_ID}
+  
+  test_on_fail_step:
+    run: exit 1
+  
+  test_on_fail_action:
+  name: Test on Fail
+  run: echo "Hello Error!"
+  when: on_fail
 
 # Invoke jobs via workflows
 # See: https://circleci.com/docs/2.0/configuration-reference/#workflows
@@ -117,4 +125,5 @@ workflows:
           requires:
             - save_hello_world_output
       - test_command_in_job
+      - test_on_fail_step
       
